apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: docker-web-app
  name: docker-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: docker-web-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: docker-web-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: sqlcontainerdb
            - name: DB_NAME
              value: DockerSQLDatabase
            - name: DB_SA_PASSWORD
              value: badfather2024@@
            - name: DB_USER_ID
              value: SA
          image: aksdemoreg.azurecr.io/dockerwebapp:latest
          name: docker-web-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
         - name: acr-secret    
    
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: docker-web-app
  name: docker-web-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: docker-web-app
  type: LoadBalancer  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sqlcontainerdb
  name: sqlcontainerdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sqlcontainerdb
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: sqlcontainerdb
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: badfather2024@@
          image: mcr.microsoft.com/mssql/server:2022-latest
          name: docker-container-database
          ports:
            - containerPort: 1433
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: sqlcontainerdb
  name: sqlcontainerdb
spec:
  ports:
    - name: "1433"
      port: 1433
      targetPort: 1433
  selector:
    io.kompose.service: sqlcontainerdb
  type: ClusterIP  
