apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessModes }}
  azureFile:
    secretName: {{ .Values.pv.secretName }}
    shareName: {{ .Values.pv.shareName }}
    readOnly: false
  persistentVolumeReclaimPolicy: {{ .Values.pv.reclaimPolicy }}