apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.azureSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  azurestorageaccountname: c3FscHZjc3RvcmFnZQ==
  azurestorageaccountkey: WWJidlIvYkFNaWFUdG5MWmNHdEo2Zzk1bERYVkhhQURxSjkzaFlKc1ZYOThwd1VWZnBwTUNqYnVBeGFJaG5UKzFzZytETFN6U0FiRStBU3RhcjBSenc9PQ==