apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.webApp.name }}
  name: {{ .Values.webApp.name }}
spec:
  ports:
    - name: "8080"
      port: {{ .Values.webApp.servicePort }}
      targetPort: {{ .Values.webApp.targetPort }}
  selector:
    app: {{ .Values.webApp.name }}
  type: {{ .Values.webApp.serviceType }}