apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.sqlAppconfigMap.name }}
  namespace: {{ .Values.namespace }}
data:
  # Configuration values can be stored as plain key-value pairs
  MSSQL_SA_PASSWORD: "{{ .Values.sqlAppconfigMap.dbRootPassword }}"
