apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.sqlApp.name }}
  name: {{ .Values.sqlApp.name }}
spec:
  ports:
    - name: "1433"
      port: {{ .Values.sqlApp.servicePort }}
      targetPort: {{ .Values.sqlApp.targetPort }}
  selector:
    app: {{ .Values.sqlApp.name }}
  type: {{ .Values.sqlApp.serviceType }}