apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
  namespace: my-aks-namespace-ado
type: Opaque
data:
  azurestorageaccountname: c3FscHZjc3RvcmFnZQ==
  azurestorageaccountkey: WWJidlIvYkFNaWFUdG5MWmNHdEo2Zzk1bERYVkhhQURxSjkzaFlKc1ZYOThwd1VWZnBwTUNqYnVBeGFJaG5UKzFzZytETFN6U0FiRStBU3RhcjBSenc9PQ==