apiVersion: v1
kind: Service
metadata:
  labels:
    app: docker-web-app
  name: docker-web-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: docker-web-app
  type: LoadBalancer