apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-web-app
  name: docker-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-web-app
  template:
    metadata:
      labels:
        app: docker-web-app
    spec:
      containers:
        - env:
            - name: DB_HOST
              valueFrom: 
                configMapKeyRef:
                  key: DB_HOST
                  name: docker-app-configmap
            - name: DB_NAME
              valueFrom: 
                configMapKeyRef:
                  key: DB_NAME
                  name: docker-app-configmap
            - name: DB_SA_PASSWORD
              valueFrom: 
                secretKeyRef:
                  key: DB_SA_PASSWORD
                  name: docker-app-secret
            - name: DB_USER_ID
              valueFrom: 
                configMapKeyRef:
                  key: DB_USER_ID
                  name: docker-app-configmap
          image: aksdemoreg.azurecr.io/dockerwebapp:latest
          name: docker-web-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      imagePullSecrets:
         - name: acr-secret